/**
 * Budynki Fazy 2 — rysowane ręcznie (docs/architecture.md „Faza 2 — assets").
 *
 * Kotwica wszystkich budynków: `{ x: 0.5, y: 1 }` = DOLNY NAROŻNIK FOOTPRINTU, czyli punkt
 * siatki `(x + w, y + h)`. Pozycjonowanie w renderze:
 *   const p = gridToScreen(x + w, y + h);           // dolny narożnik diamentu footprintu
 *   left = p.x - 0.5 * frame.w;   top = p.y - frame.h;
 * Dla 1×1 (`tower_1`, 32×48) to dolny narożnik kafla (x+1, y+1); dla 2×2 (`sawmill`,
 * `generator`, 64×48) — dolny narożnik kafla (x+1, y+1) footprintu 2×2, czyli punkt (x+2, y+2).
 *
 * Światło pada z góry-lewej: wierzch najjaśniejszy, ściana SW (dół-lewo) jaśniejsza od SE
 * (dół-prawo) — ta sama reguła co w ścianach klifu i w murze. Kontur 1 px `black`.
 */
import { PALETTE } from './palette.ts';
import { ANCHOR_FOOT, sprite, type SpriteDef } from './sprite.ts';

/**
 * Wspólna paleta budynków. Kamień: L/g/s/d/n. Drewno: T/l/b/w. Dach: c/r. Miedź: y.
 * Kryształ: C/W/B. o = kontur, e = światło (cream), m = mech.
 */
const BUILD = {
  L: PALETTE.lightGrey,
  g: PALETTE.grey,
  s: PALETTE.slate,
  d: PALETTE.darkSlate,
  n: PALETTE.navy,
  o: PALETTE.black,
  T: PALETTE.tan,
  l: PALETTE.leather,
  b: PALETTE.brown,
  w: PALETTE.darkBrown,
  e: PALETTE.cream,
  c: PALETTE.clay,
  r: PALETTE.rust,
  y: PALETTE.amber,
  C: PALETTE.cyan,
  W: PALETTE.white,
  B: PALETTE.darkBlue,
  m: PALETTE.darkGreen,
};

/** Tartak 2×2 (64×48): drewniana chata z czterospadowym dachem, kołem piły i stosem desek. */
export const sawmill: SpriteDef = sprite({
  name: 'sawmill',
  anchor: ANCHOR_FOOT,
  palette: BUILD,
  frames: [
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '.............................oo.................................',
      '...........................oocroo...............................',
      '..........................ocwcrwro..............................',
      '........................oocccwwrrroo............................',
      '......................ooccccccrrrrrroo..........................',
      '.....................occcwwcccrrrwwrrro.........................',
      '...................ooccccccwwcrwwrrrrrroo.......................',
      '.................ooccwwccccccwwrrrrrrwwrroo.....................',
      '................occccccwwcccccrrrrrwwrrrrrro....................',
      '..............oocwwccccccwwcccrrrwwrrrrrrwwroo..................',
      '............oocccccwwccccccwwcrwwrrrrrrwwrrrrroo................',
      '...........ocwwccccccwwccccccwwrrrrrrwwrrrrrrwwro...............',
      '.........ooccccwwccccccwwcccccrrrrrwwrrrrrrwwrrrroo.............',
      '.......oocwccccccwwccccccwwcccrrrwwrrrrrrwwrrrrrrwroo...........',
      '......occccwwccccccwwccccccwwcrwwrrrrrrwwrrrrrrwwrrrro..........',
      '......occccccwwccccccwwccccccwwrrrrrrwwrrrrrrwwrrrrrro..........',
      '.......owccccccwwccccccwwcccccrrrrrwwrrrrrrwwrrrrrrwo...........',
      '.......owlwccccccwwccccccwwcccrrrwwrrrrrrwwrrrrggggbo...........',
      '.......owlllwccccccwwccccccwwcrwwrrrrrrwwrrrrrggggggo...........',
      '.......owlllwlwccccccwwccccccwwrrrrrrwwrrrrrrgggggggo...........',
      '.......owlllwlllwccccccwwcccccrrrrrwwrrrrrrwggooLooggo..........',
      '.......owlllwlllwlwccccccwwcccrrrwwrrrrrrwbbgoLLgLLogo..........',
      '.......owlllwlllwlllwccccccwwcrwwrrrrrrwwbbgoLggggggogo.........',
      '.......owlllwwwlwlllwlwccccccwwrrrrrrwbbwbbgoLgdddggogo.........',
      '.......owlllwwbwwlllwlllwcccccrrrrrwwbbbwbboLggdndggLoo.........',
      '.......owlllwwbbbwwlwlllwlwcccrrrwbbwbbbwbboLggdnnddLoo.........',
      '.......owlllwwbbbbbwwlllwlllwcrwwbbbwbbbwbboLggddndggoo.........',
      '.......owlllwwwbbbbwwlllwlllwlbbwbbbwbbbwbbgoLgdddggogo.........',
      '........oollwwbwwbbwwlllwlllwlbbwbbbwbbbwbbboLggggggoo..........',
      '..........oowwbbbwwwwlllwlllwlbbwbbbwbbbwbbbgoLLgLLogo..........',
      '............owbbbbbwwlllwlllwlbbwbbbwbbbwbbbwgooLoogo...........',
      '..............obbbbwwlllwlllwlbbwbbbwbbbwbbTTbgggggo............',
      '................obbwwlllwlllwlbbwbbbwbbbwTTTTTTggoo.............',
      '..................owwlllwlllwlbbwbbbwbbTTTTTTTTTo...............',
      '....................oollwlllwlbbwbbbwblllllllllllo..............',
      '......................oowlllwlbbwbbbooTTTTTTTTTllo..............',
      '........................oollwlbbwboo..ollllllwwwwo..............',
      '..........................oowlbboo....oTTTTTlllllo..............',
      '............................oooo.......ooTTTllloo...............',
      '.........................................ooTloo.................',
      '...........................................oo...................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
  ],
});

/** Generator 2×2 (64×48): kamienna wieżyczka z miedzianą cewką i kryształem. */
export const generator: SpriteDef = sprite({
  name: 'generator',
  anchor: ANCHOR_FOOT,
  palette: BUILD,
  frames: [
    [
      '................................o...............................',
      '...............................oCo..............................',
      '..............................oCWCo.............................',
      '.............................oCWWCCo............................',
      '............................oCWWCCCCo...........................',
      '...........................oCWWCCCCBBo..........................',
      '...........................oCWCCCCBBBo..........................',
      '...........................oCCCCCBBBBo..........................',
      '............................oCCCBBBBo...........................',
      '............................ooCCBBBo............................',
      '.........................oyyyyyyyyyyyyo.........................',
      '.........................occcccccccccco.........................',
      '............................odddnnno............................',
      '............................odddnnno............................',
      '.......................oyyyyyyyyyyyyyyyyo.......................',
      '.......................occcccccccccccccco.......................',
      '............................odddnnno............................',
      '............................odddnnno............................',
      '.....................oyyyyyyyyyyyyyyyyyyyyo.....................',
      '.....................occcccccccccccccccccco.....................',
      '................oLLL........odddnnno........LLLo................',
      '................oggLLLLLLLLLLLLLLLLLLLLLLLLLLdso................',
      '................oddggLLLLLLLLLLLLLLLLLLLLLLssddo................',
      '................ogddddgLLLLLLLLLLLLLLLLLLssddsso................',
      '................ogdggddggLLLLLLLLLLLLLLdsddsssso................',
      '................ogdggggddggLLLLLLLLLLssddsdsssso................',
      '................ogdgggggddddgLLLLLLssddsssdsssso................',
      '................oddgggggdggddggLLdsddsssssdssddo................',
      '................oggddgggdggggddgsddsdsssssddddso................',
      '................oggggddgdgggggdddsssdssssddssdso................',
      '................oggggdgodgggggdgssssdssddssssdso................',
      '................oggggdoCoodgggdgssssddddsssssdso................',
      '................oddggdoCCCoddgdgsssddssdsssssddo................',
      '................ogddddoCBBCogddgsddssssdsssddsso................',
      '................ogdggdoCBBCogggdddsssssdsddsssso................',
      '................ogdggggoCCCoggggsdsssssddsdsssso................',
      '.................oogggggooCoggggsdsssddsssdssoo.................',
      '...................oogggdgoddgggsdsddsssssdoo...................',
      '.....................oogdggggddgsddsdssssoo.....................',
      '.......................oogggggdddsssdssoo.......................',
      '.........................oogggdgssssdoo.........................',
      '...........................oogdgsssoo...........................',
      '.............................oogsoo.............................',
      '...............................oo...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
  ],
});

/** Wieża strażnicza 1×1 (32×48): kamienny trzon z blankami. Poziom 2 — Faza 4. */
export const tower_1: SpriteDef = sprite({
  name: 'tower_1',
  anchor: ANCHOR_FOOT,
  palette: BUILD,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '...............oo...............',
      '.............ooLLoo.............',
      '...........ooLLLLLLoo...........',
      '...........ogLLLLLLso...........',
      '.......ooo.ogggLLssso.ooo.......',
      '.....ooLLLoLggggssssLoLLLoo.....',
      '....oLLLLLLLsgggsssgLLLLLLLo....',
      '....oggLLLsssggLLssgggLLLsso....',
      '....ogggsssssLLLLLLggggsssso....',
      '....ogggsssLLLLLLLLLLggsssso....',
      '....ogggsssggLLLLLLssggsssso....',
      '....ogggssLggggLLssssLgsssso....',
      '....oddggLLgggggsssssLLssddo....',
      '....ogddddggggggsssssdsddsso....',
      '....ogdggddgggggsssssddsdsso....',
      '....ogdggggddgggsssddsssdsso....',
      '....ogdgggggddddsddsssssdsso....',
      '....oddgggggdggddsdsssssdddo....',
      '....oggddoogdgggssdssssddsso....',
      '....oggggnngdgggssdssddsssso....',
      '....oggggnnddgggssdddoosssso....',
      '....oggggnnggddgsddssnnsssso....',
      '....oddggooggggddssssnnssddo....',
      '....ogddddgggggdsssssnnddsso....',
      '....ogdggddggggdsssssoosdsso....',
      '....ogdggggddggdsssddsssdsso....',
      '....ogdgggggddddsddsssssdsso....',
      '....oddgggggdggddsdsssssdddo....',
      '....oggddgggdgggssdssssddsso....',
      '....oggggddgdgggssdssddsssso....',
      '....oggggdgddgggssddddssssso....',
      '....oggggdoogddgsddssdssssso....',
      '....oddggdnnoogddssssdsssddo....',
      '....ogddddnnnnoosssssdsddsso....',
      '....ogdggdnnnnnnsssssddsdsso....',
      '....ogdgggnnnnnnsssddsssdsso....',
      '.....oogggnnnnnnsddsssssdoo.....',
      '.......oognnnnnndsdssssoo.......',
      '.........ooonnnnssdssoo.........',
      '...........ooonnssdoo...........',
      '.............ooosoo.............',
      '...............oo...............',
      '................................',
      '................................',
    ],
  ],
});
