/**
 * WYGENEROWANE przez `npx tsx scripts/gen-grids.ts` — edytuj generator, nie ten plik.
 *
 * Mur z auto-tilingiem (docs/architecture.md, Faza 2): `wall_0` … `wall_15`, indeks = maska
 * N|E|S|W (1|2|4|8) sąsiednich murów. N = krawędź górna-prawa kafla, E = dolna-prawa,
 * S = dolna-lewa, W = górna-lewa.
 *
 * Płótno 32×32: dolne 16 wierszy to dokładnie bounding box diamentu kafla,
 * górne 16 to zapas na wysokość muru. Kotwica (pivot) = ŚRODEK KAFLA, czyli
 * `{ x: 0.5, y: 24 / 32 }` = { 0.5, 0.7500 }:
 *   left = screenX(środek kafla) − 16
 *   top  = screenY(środek kafla) − 24
 * (na wywyższeniu jeszcze `− elevation × ELEV_PX`, jak wszystkie propy).
 *
 * Geometria: słupek 18 px nad ziemią, podstawa 10 px szerokości na ekranie;
 * segment do środka krawędzi — 14 px wysokości, 6 px szerokości.
 * Segment kończy się DOKŁADNIE na krawędzi kafla, a kontur na styku jest pominięty
 * (liczony z sumy muru i „duchów" sąsiadów), więc sąsiednie kafle sklejają się w ciągłą ścianę
 * — pilnuje tego `tests/assets/walls.test.ts`.
 */
import { PALETTE } from './palette.ts';
import { sprite, type Anchor, type SpriteDef } from './sprite.ts';

/** Środek kafla leży 24 px od góry sprite'a (8 px nad dolną krawędzią diamentu). */
export const ANCHOR_WALL: Anchor = { x: 0.5, y: 24 / 32 };

/**
 * Kamień: L = światło wierzchu, g = baza wierzchu / ściana S, s = spoina S / baza ściany E,
 * d = spoina ściany E, o = kontur. Ściana S (zwrócona w +gy, ekranowo dół-lewo) jest jaśniejsza
 * od E (+gx, dół-prawo) — to ta sama reguła światła, co w ścianach klifu.
 *
 * Kontur to `navy`, nie `darkSlate`: `darkSlate` jest już spoiną ściany E, a kontur musi być
 * o krok ciemniejszy od najciemniejszej ściany — inaczej sylwetka muru ginie na tle ściany E
 * i nie da się odróżnić fugi od szwu między kaflami (patrz `tests/assets/walls.test.ts`).
 */
const STONE = {
  L: PALETTE.lightGrey,
  g: PALETTE.grey,
  s: PALETTE.slate,
  d: PALETTE.darkSlate,
  o: PALETTE.navy,
};

/** Rusztowanie: T = pomost, l = deska oświetlona, b = deska w cieniu, o = słupek/kontur. */
const SCAFFOLD = {
  T: PALETTE.tan,
  l: PALETTE.leather,
  b: PALETTE.brown,
  o: PALETTE.darkBrown,
};

export const wall_0: SpriteDef = sprite({
  name: 'wall_0',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '............ooggggoo............',
      '...........oLLggggLLo...........',
      '...........oggLLLLsso...........',
      '...........ogggsdssso...........',
      '...........ogggsdssso...........',
      '...........ossgsdsddo...........',
      '...........ogsssdddso...........',
      '...........ogsggssdso...........',
      '...........ogsggssdso...........',
      '...........ogsggssdso...........',
      '...........ossggssddo...........',
      '...........oggssddsso...........',
      '...........ogggsdssso...........',
      '...........ogggsdssso...........',
      '...........ogggsdssso...........',
      '...........ossgsdsddo...........',
      '...........ogsssdddso...........',
      '...........ogsggssdso...........',
      '...........ogsggssdso...........',
      '............ooggssoo............',
      '..............oooo..............',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_1: SpriteDef = sprite({
  name: 'wall_1',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '............ooggggoooLg.........',
      '...........oLLggggLLdLLLg.......',
      '...........oggLLLLssdLLLLLg.....',
      '...........ogggsdsssdgLLLsd.....',
      '...........ogggsdsssdLgdssd.....',
      '...........ossgsdsddssddssd.....',
      '...........ogsssdddsssddssd.....',
      '...........ogsggssdsssddsdd.....',
      '...........ogsggssdsssdddds.....',
      '...........ogsggssdsdddsdds.....',
      '...........ossggssddddssdds.....',
      '...........oggssddssddssdds.....',
      '...........ogggsdsssddssddd.....',
      '...........ogggsdsssddsddsd.....',
      '...........ogggsdsssddddssd.....',
      '...........ossgsdsddssddssd.....',
      '...........ogsssdddsssddsoo.....',
      '...........ogsggssdsssdoo.......',
      '...........ogsggssdssoo.........',
      '............ooggssooo...........',
      '..............oooo..............',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_2: SpriteDef = sprite({
  name: 'wall_2',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '............ooggggoo............',
      '...........oLLggggLLo...........',
      '...........oggLLLLsso...........',
      '...........ogggsdssso...........',
      '...........ogggsdgLLo...........',
      '...........ossggLLLLLoo.........',
      '...........oggLLLLLLggLoo.......',
      '...........ogsgLLLggLLLLLoo.....',
      '...........ogsggsgLLLLLLgss.....',
      '...........ogsggssgLLLgddss.....',
      '...........ossggssggsssddss.....',
      '...........ogssgssggsssddss.....',
      '...........oggssssggsssdddd.....',
      '...........oggssgssgsssdddd.....',
      '...........oggssggsssddssdd.....',
      '...........osgssggssgddssdd.....',
      '...........ogsssggssgddssdd.....',
      '...........ogsgssgssgddssdd.....',
      '...........ogsggssssgddddss.....',
      '............osggssgssddddss.....',
      '.............oogssggsssddss.....',
      '...............oosggsssddss.....',
      '.................oogsssdd.......',
      '...................ooss.........',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_3: SpriteDef = sprite({
  name: 'wall_3',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '............ooggggoooLg.........',
      '...........oLLggggLLdLLLg.......',
      '...........oggLLLLssdLLLLLg.....',
      '...........ogggsdsssdgLLLsd.....',
      '...........ogggsdgLLLLgdssd.....',
      '...........ossggLLLLLLgdssd.....',
      '...........oggLLLLLLggLLLsd.....',
      '...........ogsgLLLggLLLLLLg.....',
      '...........ogsggsgLLLLLLgss.....',
      '...........ogsggssgLLLgddss.....',
      '...........ossggssggsssddss.....',
      '...........ogssgssggsssddss.....',
      '...........oggssssggsssdddd.....',
      '...........oggssgssgsssdddd.....',
      '...........oggssggsssddssdd.....',
      '...........osgssggssgddssdd.....',
      '...........ogsssggssgddssdd.....',
      '...........ogsgssgssgddssdd.....',
      '...........ogsggssssgddddss.....',
      '............osggssgssddddss.....',
      '.............oogssggsssddss.....',
      '...............oosggsssddss.....',
      '.................oogsssdd.......',
      '...................ooss.........',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_4: SpriteDef = sprite({
  name: 'wall_4',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '............ooggggoo............',
      '...........oLLggggLLo...........',
      '...........oggLLLLsso...........',
      '...........ogggsdssso...........',
      '...........oLLgsdssso...........',
      '.........ooLLLLLgsddo...........',
      '.......ooLggLLLLLLgso...........',
      '.....ooLLLLLggLLLsdso...........',
      '.....gggLLLLLLgdssdso...........',
      '.....ggssgLLLsddssdso...........',
      '.....ggssggdssddssddo...........',
      '.....ggssggdssddsddso...........',
      '.....ssssggdssddddsso...........',
      '.....ssssggdsddsddsso...........',
      '.....ssggssdddssddsso...........',
      '.....ssggsssddssddsdo...........',
      '.....ssggsssddssdddso...........',
      '.....ssggsssddsddsdso...........',
      '.....ggsssssddddssdso...........',
      '.....ggssssddsddssdo............',
      '.....ggssggdssddsoo.............',
      '.....ggssggdssdoo...............',
      '.......ssggdsoo.................',
      '.........ggoo...................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_5: SpriteDef = sprite({
  name: 'wall_5',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '............ooggggoooLg.........',
      '...........oLLggggLLdLLLg.......',
      '...........oggLLLLssdLLLLLg.....',
      '...........ogggsdsssdgLLLsd.....',
      '...........oLLgsdsssdLgdssd.....',
      '.........ooLLLLLgsddssddssd.....',
      '.......ooLggLLLLLLgsssddssd.....',
      '.....ooLLLLLggLLLsdsssddsdd.....',
      '.....gggLLLLLLgdssdsssdddds.....',
      '.....ggssgLLLsddssdsdddsdds.....',
      '.....ggssggdssddssddddssdds.....',
      '.....ggssggdssddsddsddssdds.....',
      '.....ssssggdssddddssddssddd.....',
      '.....ssssggdsddsddssddsddsd.....',
      '.....ssggssdddssddssddddssd.....',
      '.....ssggsssddssddsdssddssd.....',
      '.....ssggsssddssdddsssddsoo.....',
      '.....ssggsssddsddsdsssdoo.......',
      '.....ggsssssddddssdssoo.........',
      '.....ggssssddsddssdoo...........',
      '.....ggssggdssddsoo.............',
      '.....ggssggdssdoo...............',
      '.......ssggdsoo.................',
      '.........ggoo...................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_6: SpriteDef = sprite({
  name: 'wall_6',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '............ooggggoo............',
      '...........oLLggggLLo...........',
      '...........oggLLLLsso...........',
      '...........ogggsdssso...........',
      '...........oLLgsdgLLo...........',
      '.........ooLLLLLgLLLLoo.........',
      '.......ooLggLLLLLLgLggLoo.......',
      '.....ooLLLLLggLLLsdgLLLLLoo.....',
      '.....gggLLLLLLgdssdLLLLLgss.....',
      '.....ggssgLLLsddssdLLLgddss.....',
      '.....ggssggdssddssdgsssddss.....',
      '.....ggssggdssddsddgsssddss.....',
      '.....ssssggdssddddsgsssdddd.....',
      '.....ssssggdsddsddsgsssdddd.....',
      '.....ssggssdddssddsssddssdd.....',
      '.....ssggsssddssddssgddssdd.....',
      '.....ssggsssddssdddsgddssdd.....',
      '.....ssggsssddsddsdsgddssdd.....',
      '.....ggsssssddddssdsgddddss.....',
      '.....ggssssddsddssdssddddss.....',
      '.....ggssggdssddssdgsssddss.....',
      '.....ggssggdssdoosggsssddss.....',
      '.......ssggdsoo..oogsssdd.......',
      '.........ggoo......ooss.........',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_7: SpriteDef = sprite({
  name: 'wall_7',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '............ooggggoooLg.........',
      '...........oLLggggLLdLLLg.......',
      '...........oggLLLLssdLLLLLg.....',
      '...........ogggsdsssdgLLLsd.....',
      '...........oLLgsdgLLLLgdssd.....',
      '.........ooLLLLLgLLLLLgdssd.....',
      '.......ooLggLLLLLLgLggLLLsd.....',
      '.....ooLLLLLggLLLsdgLLLLLLg.....',
      '.....gggLLLLLLgdssdLLLLLgss.....',
      '.....ggssgLLLsddssdLLLgddss.....',
      '.....ggssggdssddssdgsssddss.....',
      '.....ggssggdssddsddgsssddss.....',
      '.....ssssggdssddddsgsssdddd.....',
      '.....ssssggdsddsddsgsssdddd.....',
      '.....ssggssdddssddsssddssdd.....',
      '.....ssggsssddssddssgddssdd.....',
      '.....ssggsssddssdddsgddssdd.....',
      '.....ssggsssddsddsdsgddssdd.....',
      '.....ggsssssddddssdsgddddss.....',
      '.....ggssssddsddssdssddddss.....',
      '.....ggssggdssddssdgsssddss.....',
      '.....ggssggdssdoosggsssddss.....',
      '.......ssggdsoo..oogsssdd.......',
      '.........ggoo......ooss.........',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_8: SpriteDef = sprite({
  name: 'wall_8',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '.........gLoooggggoo............',
      '.......gLLLsLLggggLLo...........',
      '.....gLLLLLsggLLLLsso...........',
      '.....sgLLLgsgggsdssso...........',
      '.....sggsgLsgggsdssso...........',
      '.....sggssggssgsdsddo...........',
      '.....sggssgggsssdddso...........',
      '.....ssgssgggsggssdso...........',
      '.....gssssgggsggssdso...........',
      '.....gssgsssgsggssdso...........',
      '.....gssggssssggssddo...........',
      '.....gssggssggssddsso...........',
      '.....sssggssgggsdssso...........',
      '.....sgssgssgggsdssso...........',
      '.....sggssssgggsdssso...........',
      '.....sggssggssgsdsddo...........',
      '.....oogssgggsssdddso...........',
      '.......oosgggsggssdso...........',
      '.........ooggsggssdso...........',
      '...........oooggssoo............',
      '..............oooo..............',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_9: SpriteDef = sprite({
  name: 'wall_9',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '.........gLoooggggoooLg.........',
      '.......gLLLsLLggggLLdLLLg.......',
      '.....gLLLLLsggLLLLssdLLLLLg.....',
      '.....sgLLLgsgggsdsssdgLLLsd.....',
      '.....sggsgLsgggsdsssdLgdssd.....',
      '.....sggssggssgsdsddssddssd.....',
      '.....sggssgggsssdddsssddssd.....',
      '.....ssgssgggsggssdsssddsdd.....',
      '.....gssssgggsggssdsssdddds.....',
      '.....gssgsssgsggssdsdddsdds.....',
      '.....gssggssssggssddddssdds.....',
      '.....gssggssggssddssddssdds.....',
      '.....sssggssgggsdsssddssddd.....',
      '.....sgssgssgggsdsssddsddsd.....',
      '.....sggssssgggsdsssddddssd.....',
      '.....sggssggssgsdsddssddssd.....',
      '.....oogssgggsssdddsssddsoo.....',
      '.......oosgggsggssdsssdoo.......',
      '.........ooggsggssdssoo.........',
      '...........oooggssooo...........',
      '..............oooo..............',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_10: SpriteDef = sprite({
  name: 'wall_10',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '.........gLoooggggoo............',
      '.......gLLLsLLggggLLo...........',
      '.....gLLLLLsggLLLLsso...........',
      '.....sgLLLgsgggsdssso...........',
      '.....sggsgLsgggsdgLLo...........',
      '.....sggssggssggLLLLLoo.........',
      '.....sggssggggLLLLLLggLoo.......',
      '.....ssgssgggsgLLLggLLLLLoo.....',
      '.....gssssgggsggsgLLLLLLgss.....',
      '.....gssgsssgsggssgLLLgddss.....',
      '.....gssggssssggssggsssddss.....',
      '.....gssggssgssgssggsssddss.....',
      '.....sssggssggssssggsssdddd.....',
      '.....sgssgssggssgssgsssdddd.....',
      '.....sggssssggssggsssddssdd.....',
      '.....sggssggsgssggssgddssdd.....',
      '.....oogssgggsssggssgddssdd.....',
      '.......oosgggsgssgssgddssdd.....',
      '.........ooggsggssssgddddss.....',
      '...........oosggssgssddddss.....',
      '.............oogssggsssddss.....',
      '...............oosggsssddss.....',
      '.................oogsssdd.......',
      '...................ooss.........',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_11: SpriteDef = sprite({
  name: 'wall_11',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '.........gLoooggggoooLg.........',
      '.......gLLLsLLggggLLdLLLg.......',
      '.....gLLLLLsggLLLLssdLLLLLg.....',
      '.....sgLLLgsgggsdsssdgLLLsd.....',
      '.....sggsgLsgggsdgLLLLgdssd.....',
      '.....sggssggssggLLLLLLgdssd.....',
      '.....sggssggggLLLLLLggLLLsd.....',
      '.....ssgssgggsgLLLggLLLLLLg.....',
      '.....gssssgggsggsgLLLLLLgss.....',
      '.....gssgsssgsggssgLLLgddss.....',
      '.....gssggssssggssggsssddss.....',
      '.....gssggssgssgssggsssddss.....',
      '.....sssggssggssssggsssdddd.....',
      '.....sgssgssggssgssgsssdddd.....',
      '.....sggssssggssggsssddssdd.....',
      '.....sggssggsgssggssgddssdd.....',
      '.....oogssgggsssggssgddssdd.....',
      '.......oosgggsgssgssgddssdd.....',
      '.........ooggsggssssgddddss.....',
      '...........oosggssgssddddss.....',
      '.............oogssggsssddss.....',
      '...............oosggsssddss.....',
      '.................oogsssdd.......',
      '...................ooss.........',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_12: SpriteDef = sprite({
  name: 'wall_12',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '.........gLoooggggoo............',
      '.......gLLLsLLggggLLo...........',
      '.....gLLLLLsggLLLLsso...........',
      '.....sgLLLgsgggsdssso...........',
      '.....sggsgLLLLgsdssso...........',
      '.....sggsgLLLLLLgsddo...........',
      '.....sgLLLggLLLLLLgso...........',
      '.....gLLLLLLggLLLsdso...........',
      '.....gggLLLLLLgdssdso...........',
      '.....ggssgLLLsddssdso...........',
      '.....ggssggdssddssddo...........',
      '.....ggssggdssddsddso...........',
      '.....ssssggdssddddsso...........',
      '.....ssssggdsddsddsso...........',
      '.....ssggssdddssddsso...........',
      '.....ssggsssddssddsdo...........',
      '.....ssggsssddssdddso...........',
      '.....ssggsssddsddsdso...........',
      '.....ggsssssddddssdso...........',
      '.....ggssssddsddssdo............',
      '.....ggssggdssddsoo.............',
      '.....ggssggdssdoo...............',
      '.......ssggdsoo.................',
      '.........ggoo...................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_13: SpriteDef = sprite({
  name: 'wall_13',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '.........gLoooggggoooLg.........',
      '.......gLLLsLLggggLLdLLLg.......',
      '.....gLLLLLsggLLLLssdLLLLLg.....',
      '.....sgLLLgsgggsdsssdgLLLsd.....',
      '.....sggsgLLLLgsdsssdLgdssd.....',
      '.....sggsgLLLLLLgsddssddssd.....',
      '.....sgLLLggLLLLLLgsssddssd.....',
      '.....gLLLLLLggLLLsdsssddsdd.....',
      '.....gggLLLLLLgdssdsssdddds.....',
      '.....ggssgLLLsddssdsdddsdds.....',
      '.....ggssggdssddssddddssdds.....',
      '.....ggssggdssddsddsddssdds.....',
      '.....ssssggdssddddssddssddd.....',
      '.....ssssggdsddsddssddsddsd.....',
      '.....ssggssdddssddssddddssd.....',
      '.....ssggsssddssddsdssddssd.....',
      '.....ssggsssddssdddsssddsoo.....',
      '.....ssggsssddsddsdsssdoo.......',
      '.....ggsssssddddssdssoo.........',
      '.....ggssssddsddssdoo...........',
      '.....ggssggdssddsoo.............',
      '.....ggssggdssdoo...............',
      '.......ssggdsoo.................',
      '.........ggoo...................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_14: SpriteDef = sprite({
  name: 'wall_14',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '.........gLoooggggoo............',
      '.......gLLLsLLggggLLo...........',
      '.....gLLLLLsggLLLLsso...........',
      '.....sgLLLgsgggsdssso...........',
      '.....sggsgLLLLgsdgLLo...........',
      '.....sggsgLLLLLLgLLLLoo.........',
      '.....sgLLLggLLLLLLgLggLoo.......',
      '.....gLLLLLLggLLLsdgLLLLLoo.....',
      '.....gggLLLLLLgdssdLLLLLgss.....',
      '.....ggssgLLLsddssdLLLgddss.....',
      '.....ggssggdssddssdgsssddss.....',
      '.....ggssggdssddsddgsssddss.....',
      '.....ssssggdssddddsgsssdddd.....',
      '.....ssssggdsddsddsgsssdddd.....',
      '.....ssggssdddssddsssddssdd.....',
      '.....ssggsssddssddssgddssdd.....',
      '.....ssggsssddssdddsgddssdd.....',
      '.....ssggsssddsddsdsgddssdd.....',
      '.....ggsssssddddssdsgddddss.....',
      '.....ggssssddsddssdssddddss.....',
      '.....ggssggdssddssdgsssddss.....',
      '.....ggssggdssdoosggsssddss.....',
      '.......ssggdsoo..oogsssdd.......',
      '.........ggoo......ooss.........',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

export const wall_15: SpriteDef = sprite({
  name: 'wall_15',
  anchor: ANCHOR_WALL,
  palette: STONE,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............oooo..............',
      '.........gLoooggggoooLg.........',
      '.......gLLLsLLggggLLdLLLg.......',
      '.....gLLLLLsggLLLLssdLLLLLg.....',
      '.....sgLLLgsgggsdsssdgLLLsd.....',
      '.....sggsgLLLLgsdgLLLLgdssd.....',
      '.....sggsgLLLLLLgLLLLLgdssd.....',
      '.....sgLLLggLLLLLLgLggLLLsd.....',
      '.....gLLLLLLggLLLsdgLLLLLLg.....',
      '.....gggLLLLLLgdssdLLLLLgss.....',
      '.....ggssgLLLsddssdLLLgddss.....',
      '.....ggssggdssddssdgsssddss.....',
      '.....ggssggdssddsddgsssddss.....',
      '.....ssssggdssddddsgsssdddd.....',
      '.....ssssggdsddsddsgsssdddd.....',
      '.....ssggssdddssddsssddssdd.....',
      '.....ssggsssddssddssgddssdd.....',
      '.....ssggsssddssdddsgddssdd.....',
      '.....ssggsssddsddsdsgddssdd.....',
      '.....ggsssssddddssdsgddddss.....',
      '.....ggssssddsddssdssddddss.....',
      '.....ggssggdssddssdgsssddss.....',
      '.....ggssggdssdoosggsssddss.....',
      '.......ssggdsoo..oogsssdd.......',
      '.........ggoo......ooss.........',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

/** Mur w budowie: drewniane rusztowanie bez segmentów (render używa go z alfą). */
export const wall_build: SpriteDef = sprite({
  name: 'wall_build',
  anchor: ANCHOR_WALL,
  palette: SCAFFOLD,
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............TTTT..............',
      '............TTTTTTTT............',
      '...........bTTTTTTTTo...........',
      '...........b..TTTT..o...........',
      '...........b...bo...o...........',
      '...........b...bo...o...........',
      '...........bll.bo.bbo...........',
      '...........blllbobbbo...........',
      '...........blllbobbbo...........',
      '...........b..lbob..o...........',
      '...........b...bo...o...........',
      '...........b...bo...o...........',
      '...........bll.bo.bbo...........',
      '...........blllbobbbo...........',
      '...........blllbobbbo...........',
      '...........b..lbob..o...........',
      '...........b...bo...o...........',
      '...........b...bo...o...........',
      '...........bll.bo.bbo...........',
      '...........blllbobbbo...........',
      '............lllbobbb............',
      '..............lbob..............',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  ],
});

/** `wall_0` … `wall_15` w kolejności maski — indeks = N|E|S|W (1|2|4|8). */
export const WALL_FRAMES: readonly SpriteDef[] = [
  wall_0,
  wall_1,
  wall_2,
  wall_3,
  wall_4,
  wall_5,
  wall_6,
  wall_7,
  wall_8,
  wall_9,
  wall_10,
  wall_11,
  wall_12,
  wall_13,
  wall_14,
  wall_15,
];
